# Form implementation generated from reading ui file 'ui/main.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(217, 231)
        self.verticalLayout = QtWidgets.QVBoxLayout(MainWindow)
        self.verticalLayout.setObjectName("verticalLayout")
        self.ImportButton = QtWidgets.QPushButton(parent=MainWindow)
        self.ImportButton.setObjectName("ImportButton")
        self.verticalLayout.addWidget(self.ImportButton)
        self.VerButton = QtWidgets.QPushButton(parent=MainWindow)
        self.VerButton.setObjectName("VerButton")
        self.verticalLayout.addWidget(self.VerButton)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "BsimpleHires"))
        self.ImportButton.setText(_translate("MainWindow", "导入文件"))
        self.VerButton.setText(_translate("MainWindow", "版本信息"))
