# Form implementation generated from reading ui file 'ui/ProgressBar.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ProgressBar(object):
    def setupUi(self, ProgressBar):
        ProgressBar.setObjectName("ProgressBar")
        ProgressBar.resize(500, 200)
        self.verticalLayout = QtWidgets.QVBoxLayout(ProgressBar)
        self.verticalLayout.setObjectName("verticalLayout")
        self.titleLabel = QtWidgets.QLabel(parent=ProgressBar)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.titleLabel.setFont(font)
        self.titleLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.titleLabel.setObjectName("titleLabel")
        self.verticalLayout.addWidget(self.titleLabel)
        self.currentFileLabel = QtWidgets.QLabel(parent=ProgressBar)
        self.currentFileLabel.setObjectName("currentFileLabel")
        self.verticalLayout.addWidget(self.currentFileLabel)
        self.totalProgressLabel = QtWidgets.QLabel(parent=ProgressBar)
        self.totalProgressLabel.setObjectName("totalProgressLabel")
        self.verticalLayout.addWidget(self.totalProgressLabel)
        self.progressBar = QtWidgets.QProgressBar(parent=ProgressBar)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout.addWidget(self.progressBar)
        self.statusLabel = QtWidgets.QLabel(parent=ProgressBar)
        self.statusLabel.setObjectName("statusLabel")
        self.verticalLayout.addWidget(self.statusLabel)
        self.cancelButton = QtWidgets.QPushButton(parent=ProgressBar)
        self.cancelButton.setObjectName("cancelButton")
        self.verticalLayout.addWidget(self.cancelButton)

        self.retranslateUi(ProgressBar)
        QtCore.QMetaObject.connectSlotsByName(ProgressBar)

    def retranslateUi(self, ProgressBar):
        _translate = QtCore.QCoreApplication.translate
        ProgressBar.setWindowTitle(_translate("ProgressBar", "转换进度"))
        self.titleLabel.setText(_translate("ProgressBar", "文件转换进度"))
        self.currentFileLabel.setText(_translate("ProgressBar", "当前文件: 准备中..."))
        self.totalProgressLabel.setText(_translate("ProgressBar", "总体进度: 0/0"))
        self.statusLabel.setText(_translate("ProgressBar", "状态: 等待中"))
        self.cancelButton.setText(_translate("ProgressBar", "取消"))
