# Form implementation generated from reading ui file 'ui/workPage.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_table(object):
    def setupUi(self, table):
        table.setObjectName("table")
        table.resize(1028, 314)
        table.setMaximumSize(QtCore.QSize(1100, 1000))
        self.verticalLayout = QtWidgets.QVBoxLayout(table)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tableWidget = QtWidgets.QTableWidget(parent=table)
        self.tableWidget.setEnabled(True)
        self.tableWidget.setMaximumSize(QtCore.QSize(1200, 1000))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(10)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(9, item)
        self.verticalLayout.addWidget(self.tableWidget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ImportButton = QtWidgets.QPushButton(parent=table)
        self.ImportButton.setObjectName("ImportButton")
        self.horizontalLayout.addWidget(self.ImportButton)
        self.WorkButton = QtWidgets.QPushButton(parent=table)
        self.WorkButton.setObjectName("WorkButton")
        self.horizontalLayout.addWidget(self.WorkButton)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(table)
        QtCore.QMetaObject.connectSlotsByName(table)

    def retranslateUi(self, table):
        _translate = QtCore.QCoreApplication.translate
        table.setWindowTitle(_translate("table", "BsimpleHires"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("table", "选择"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("table", "文件名"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("table", "时长"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("table", "大小"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("table", "分辨率"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("table", "帧率"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("table", "视频格式"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("table", "音频格式"))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("table", "采样率"))
        item = self.tableWidget.horizontalHeaderItem(9)
        item.setText(_translate("table", "音频码率"))
        self.ImportButton.setText(_translate("table", "导入文件"))
        self.WorkButton.setText(_translate("table", "格式转换"))
